#!/usr/bin/env python

import typer
from rich.console import Console
from rich.table import Table
from model import Entry
from database import get_all_entries, delete_entry, insert_entry, complete_entry, update_entry

console = Console()

app = typer.Typer()


@app.command(short_help="Adds an entry to the list")
def add(title: str, category: str):
    typer.echo(f"Adding entry {title}, {category}...")
    entry = Entry(title, category)
    insert_entry(entry)
    show()


@app.command(short_help="Deletes an entry from the list")
def delete(position: int):
    typer.echo(f"Deleting entry at position {position}...")
    # index in UI begins at 1, but in database begins at 0
    delete_entry(position-1)
    show()


@app.command(short_help="Update an entry's properties")
def update(position: int, title: str = None, category: str = None):
    typer.echo(f"Updating {position}...")
    update_entry(position-1, title, category)
    show()


@app.command(short_help="Marks an entry as completed")
def complete(position: int):
    typer.echo(f"Marking {position} as completed...")
    complete_entry(position-1)
    show()


@app.command(short_help="Displays all of the entries in the list")
def show():
    entries = get_all_entries()
    console.print("[bold magenta]Entries![/bold magenta]", "💻")

    table = Table(show_header=True, header_style="bold blue")
    table.add_column("#", style="dim", width=6)
    table.add_column("Title", min_width=20)
    table.add_column("Category", min_width=12, justify="right")
    table.add_column("Done", min_width=12, justify="right")

    def get_category_color(category):
        COLORS = {
            "Anime": "cyan",
            "Manga": "cyan",
            "TV": "red",
            "Movie": "red",
        }

        if category in COLORS:
            return COLORS[category]
        return "white"

    for index, entry in enumerate(entries, start=1):
        c = get_category_color(entry.category)
        is_done_str = "✅" if entry.status == 2 else "⏳"
        table.add_row(str(index), entry.title,
                      f"[{c}]{entry.category}[/{c}]", is_done_str)
    console.print(table)


if __name__ == "__main__":
    app()
